sudo: required
services: [ docker ]
branches: 
  only: [ master ]

before_install:
- sh ci/enviroment.sh

script:
- sh ci/build.sh
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- sh ci/push.sh

after_success:
- sh succes.sh
